### PR TITLE
Fix fpillet/NSLogger#168

### PR DESCRIPTION
**Pull request by rvi**
Fix for fpillet/NSLogger#168

### CODE REVIEW

**Comment by rvi** [comment]
@fpillet Done.

For getting the `colorForMessage`, I check `[message message]` instead of `[message description]` : 

```Objc
 + (NSColor *)colorForMessage:(LoggerMessage *)message
 {
     return [self colorForString:[message message]];
 }
```

**Comment by rvi** [comment]
@fpillet is there a reason why you don't want to merge this pull request ? If so, please tell me, I'll fix the code accordingly.

Cheers.

**Comment by fpillet** [comment]
Hi Rémy,

Sorry for the delay -- work has been hectic since I came back from vacation and I lacked time to take care of incoming requests.

It's merged now. I'll push out a new binary release as soon as possible. 
Thanks !
Florent

**Comment by rvi** [comment]
No worries, Thanks a lot Florent !

**Pull request merged**
