### PR TITLE
Fix parsing 64 bits encoded level

### PR DESCRIPTION
**Pull request by c0diq**
Values being sent from a 64 bits client were incorrectly read as 32 bits resulting in all levels being displayed as errors.

### CODE REVIEW

**Comment by fpillet** [comment]
Wow. Didn't know something that bad had been lurking there for so long. Thanks!

**Comment by fpillet** [comment]
Actually the code assumed that levels are always at works Int32, which is true in the original logger code but you're right anyway. Never trust the wire.

**Comment by c0diq** [comment]
Would it be possible to make a new release? The last one was may 2017.

**Comment by fpillet** [comment]
Yes, will do in the coming days.

**Comment by c0diq** [comment]
Any way we can get a new release please?

**Comment by fpillet** [comment]
Sure, once I sort out the Carthage mess. The `import NSLogger` statement that was added for Carthage in Logger.swift triggers an Xcode warning when building for Cocoapods, which trips up `pod trunk` and refuses to push.

**Pull request merged**
