### PR TITLE
Switch to multiplatform, single-scheme Xcode project structure

### PR DESCRIPTION
**Pull request by 0xced**
See http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

### CODE REVIEW

**Comment by 0xced** [comment]
Not sure how this is going to work with buddybuild… Does it only build the master branch?

**Comment by fpillet** [comment]
Not sure, BuddyBuild is all in @MonsieurDart 's hands ... We'll check it out separately :)

**Comment by MonsieurDart** [comment]
For now, buddybuild builds on my fork of NSLogger, on master branch. I will check today if I cannot build on the @fpillet's repo and update the target for this pull request.

**Comment by MonsieurDart** [comment]
Done: https://github.com/fpillet/NSLogger/commit/f3b374face94de19a824af296b3c8f8490e9fffa

(It seems that I have "collaborator" rights on the repo. Florent, I hope it's not a problem that I directly pushed this small change…) 😉

**Comment by fpillet** [comment]
@MonsieurDart Perfect thanks! That's why you (and Cédric) both have collaborator access :)

**Pull request merged**
