### PR TITLE
Cocoa client

### PR DESCRIPTION
**Pull request by 0xced**
The main point of this pull request is to enable peer-to-peer browsing without relying on private APIs. I also added the `kLoggerOption_BrowsePeerToPeer` option (on by default) to control if peer-to-peer browsing should be enabled.

Side effects of this are
* Removed `ALLOW_COCOA_USE`. I first implemented net service browsing with both CFNetServiceBrowserRef and NSNetServiceBrowser but the code became pretty much unreadable with #if ALLOW_COCOA_USE #else everywhere.
* Forced compile LoggerClient.m without ARC. Using NSNetServiceBrowser with ARC was a PITA, the code with manual retain/release is much more pleasant to the eyes.
* Made the Logger struct private and added new `LoggerGet[…]` functions instead.

### CODE REVIEW

**Comment by fpillet** [comment]
Question about disabling ARC: how will this impact users who get NSLogger through CocoaPods? and users who don't use CP? will they need to reconfigure their projects ?

**Comment by 0xced** [comment]
CocoaPods users [will not be affected](https://github.com/fpillet/NSLogger/pull/204/commits/6ffa42c95a5921a4957502fcc649c552ec6a69ca#diff-7598fb17967d8c6c65eca2333efb0794R23). Carthage users and users using NSLogger.xcodeproj [will not be affected either](https://github.com/fpillet/NSLogger/pull/204/commits/6ffa42c95a5921a4957502fcc649c552ec6a69ca#diff-a76a8f02fa72bc2b2332b971ecec2e31R301).

Only people drag&dropping `LoggerClient.m` directly in their (ARC) project will be affected. But these users need to learn how to properly integrate a library.

**Comment by fpillet** [comment]
Ok cool. And you're right, feels strange to actually *disable ARC* in this day and age, with the intent of making the code more clear :)

Thanks for these improvements!!

**Comment by 0xced** [comment]
Great! Are you planning to release a new version? The new peer-to-peer features warrants a 1.7.0 version.

**Comment by fpillet** [comment]
Sure, let me update the required files and I'll push 1.7.0

**Pull request merged**
